### ISSUE TITLE
Older projects might have a lower Java class version then 65.0

### ISSUE THREAD

**Issue by sshaaf** [Giovds/outdated-maven-plugin#18]
Many projects out there might be using older versions of Java when running this plugin. Even though 21 is the LTS, compiling this with an older Java version might be helpful.

Got an error running check with Java 17 but works fine with 23, should work with 21 too (Class version. 65.0) 
`Execution default-cli of goal com.giovds:outdated-maven-plugin:1.0.0:check failed: Unable to load the mojo 'check' in the plugin 'com.giovds:outdated-maven-plugin:1.0.0' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: com/giovds/OutdatedMavenPluginMojo has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0`

**Comment by Giovds** [comment]
It would be useful indeed, perhaps 21 is a bit too enthusiastic.

I considered 11 for a moment as well since some vendors have extended support well into 2020 and even 2030. Though I do support the idea of more frequent upgrades to LTS versions and not linger in older LTS versions. However, going back 1 LTS does seem fair.

**Comment by sshaaf** [comment]
LTS -1 sounds like a good idea. I also support the idea for more frequent upgrades. Even though lots of 8 and 11 out there. Its a balance.

**Comment by Giovds** [comment]
@sshaaf Will be included next release. Thanks for giving it a go and good the feedback!
